### ISSUE TITLE
`./start-console` won't work with non-admin user

### ISSUE THREAD

**Issue by glekner** [spadgett/console-plugin-template#3]
getting the following error trying to run `./start-console.sh`

```
Starting local OpenShift console...
Error from server (Forbidden): configmaps "monitoring-shared-config" is forbidden: User "test" cannot get resource "configmaps" in API group "" in the namespace "openshift-config-managed"
```

**Comment by spadgett** [comment]
Hey @glekner, this is fixed with the latest commit https://github.com/spadgett/console-plugin-template/commit/1b68e045da018ba72dbae7aca02081ee96676b9f. Let me know if you still see the issue.
